development:
  database:
    name: cazier-auto_development
    host: 127.0.0.1
    port: 27017

test:
  database:
    name: cazier-auto_test
    host: 127.0.0.1
    port: 27017

production:
  database:
    name: cazier-auto
    host: 127.0.0.1
    port: 27017
